services:
  postgres:
    container_name: roseitconsulting-postgres
    image: postgres
    environment:
      POSTGRES_USER: jordanmruczynski
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
  roseitapp:
    container_name: roseitapp
    image: jordanmruczynski/roseit-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
    ports:
      - "8090:80"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:
      driver: bridge
volumes:
  postgres: