server:
  port: 80
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: jordanmruczynski
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

