-- CREATE SEQUENCE customer_id_sequence;
-- FROM POSTGRESQL 10 THEY INTRODUCED 'GENERATED AS IDENTITY' TO BE CORRECTLY WITH SQL BEST PRACTICES, ~JordanM

CREATE TABLE customer(
--     id BIGINT DEFAULT nextval('customer_id_sequence') PRIMARY KEY,
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL,
    age INT NOT NULL
);